#if !canImport(ObjectiveC)
import XCTest

extension DigestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DigestTests = [
        ("testMD2", testMD2),
        ("testMD4", testMD4),
        ("testMD5", testMD5),
        ("testSHA1", testSHA1),
        ("testSHA224", testSHA224),
        ("testSHA256", testSHA256),
        ("testSHA384", testSHA384),
        ("testSHA512", testSHA512),
    ]
}

extension HMACTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HMACTests = [
        ("testMD5", testMD5),
        ("testSHA1", testSHA1),
        ("testSHA224", testSHA224),
        ("testSHA256", testSHA256),
        ("testSHA384", testSHA384),
        ("testSHA512", testSHA512),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DigestTests.__allTests__DigestTests),
        testCase(HMACTests.__allTests__HMACTests),
    ]
}
#endif
